cc_test(
  name = "tensor_create_test",
  srcs = ["tensor_create_test.cc"],
  includes = ["//src/core"],
  deps = [
    "//src/core:core",
    "@com_google_googletest//:gtest_main",
  ],
)

cc_test(
  name = "tensor_fill_test",
  srcs = ["tensor_fill_test.cc"],
  includes = ["//src/core"],
  deps = [
    "//src/core:core",
    "@com_google_googletest//:gtest_main",
  ],
)
