cc_binary(
    name = "example1",
    srcs = ["example1.cc"],
    deps = ["@eigen//:eigen"],
)

cc_binary(
    name = "eigen_chip",
    srcs = ["eigen_chip.cc"],
    deps = ["@eigen//:eigen"],
)
cc_binary(
    name = "eigen_raw",
    srcs = ["eigen_raw.cc"],
    deps = ["@eigen//:eigen"],
)
